# Generated by Django 3.1.5 on 2021-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltechniques', '0004_auto_20210122_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='answer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
