# Generated by Django 3.1.5 on 2021-01-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitaltechniques', '0006_auto_20210122_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtPostComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitaltechniques.dtpostcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitaltechniques.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
