# Generated by Django 3.1.5 on 2021-01-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computergraphics', '0003_links_mcqs_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Mcqs',
            new_name='Mcq',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
