# Generated by Django 3.1.5 on 2021-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microprocessors', '0005_mcq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/microprocessors'),
        ),
    ]
