# Generated by Django 3.1.5 on 2021-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
